services:
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - 'PGUSER=$POSTGRES_USER'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h $POSTGRES_ADDRESS']
      interval: 10s
      timeout: 5s
      retries: 5

  image-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    ports:
      - '8000:8000'
volumes:
  data:
