services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5435:5432'
    volumes:
      - data:/var/lib/postgresql/data

  image-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - default
    volumes:
      - ./images:/images
    ports:
      - '8000:8000'
volumes:
  data:
